# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-12-02T08:25:41+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class GlobalInstructions(Enum):
    If_you_select_Asserted_research_waste_or_Quoted_research_waste__the_study_will_be_INCLUDED_for_Level_2_screening_ = "If you select Asserted_research_waste or Quoted_research_waste, the study will be INCLUDED for Level 2 screening."
    If_you_select_any_other_waste_category__the_study_will_be_EXCLUDED_ = (
        "If you select any other waste category, the study will be EXCLUDED."
    )
    If_you_select_Not_sure_see_previous_step__the_study_will_be_INCLUDED_for_Level_2_screening_ = "If you select Not_sure_see_previous_step, the study will be INCLUDED for Level 2 screening."
    The_screening_system_includes_a_simulated_peer__pree__review_process_that_helps_validate_categorization_decisions__but_this_does_not_require_manual_input_from_screeners_ = "The screening system includes a simulated peer 'pree' review process that helps validate categorization decisions, but this does not require manual input from screeners."


class Step2InitialExtractedValue(Enum):
    Asserted_research_waste = "Asserted_research_waste"
    Quoted_research_waste = "Quoted_research_waste"
    Food_waste = "Food_waste"
    Hazardous_waste = "Hazardous_waste"
    Plastic_waste = "Plastic_waste"
    Garbage_management = "Garbage_management"
    Industrial_waste = "Industrial_waste"
    Wastewater = "Wastewater"
    Medical_or_surgical_waste = "Medical_or_surgical_waste"
    Healthcare_personnel_time = "Healthcare_personnel_time"
    Excess_requisition = "Excess_requisition"
    Excess_use_of_animals = "Excess_use_of_animals"
    Pharmaceutical_waste = "Pharmaceutical_waste"
    Muscle_wasting = "Muscle_wasting"
    Metabolic_waste = "Metabolic_waste"
    Crop_residue = "Crop_residue"
    Not_sure_see_previous_step = "Not_sure_see_previous_step"


class Step7FinalExtractedValue(Enum):
    Asserted_research_waste = "Asserted_research_waste"
    Quoted_research_waste = "Quoted_research_waste"
    Food_waste = "Food_waste"
    Hazardous_waste = "Hazardous_waste"
    Plastic_waste = "Plastic_waste"
    Garbage_management = "Garbage_management"
    Industrial_waste = "Industrial_waste"
    Wastewater = "Wastewater"
    Medical_or_surgical_waste = "Medical_or_surgical_waste"
    Healthcare_personnel_time = "Healthcare_personnel_time"
    Excess_requisition = "Excess_requisition"
    Excess_use_of_animals = "Excess_use_of_animals"
    Pharmaceutical_waste = "Pharmaceutical_waste"
    Muscle_wasting = "Muscle_wasting"
    Metabolic_waste = "Metabolic_waste"
    Crop_residue = "Crop_residue"
    Not_sure_see_previous_step = "Not_sure_see_previous_step"


class ExtractionField1Literal(BaseModel):
    name: Literal["Waste Type Discussed"] = Field(..., title="Name")
    description: Literal["What kind of waste is discussed in this article?"] = Field(
        ..., title="Description"
    )
    field_type: Literal["text"] = Field(..., title="Field Type")
    required: Literal["True"] = Field(..., title="Required")
    question_number: Literal["1"] = Field(..., title="Question Number")
    question_type: Literal["screening"] = Field(..., title="Question Type")
    guidance_notes: Literal[
        "Read the title and abstract carefully. Identify and describe the type of waste being discussed. Look for key terms and context clues that indicate the nature of the waste."
    ] = Field(..., title="Guidance Notes")


class ExtractionField2Literal(BaseModel):
    name: Literal["Waste Origin"] = Field(..., title="Name")
    description: Literal["Where does this kind of waste typically come from?"] = Field(
        ..., title="Description"
    )
    field_type: Literal["text"] = Field(..., title="Field Type")
    required: Literal["True"] = Field(..., title="Required")
    question_number: Literal["2"] = Field(..., title="Question Number")
    question_type: Literal["screening"] = Field(..., title="Question Type")
    guidance_notes: Literal[
        "Based on your general knowledge and the article context, identify where this kind of waste primarily originates in the real world:\n- Research settings (clinical trials, laboratories, systematic reviews, grant processes, publications)\n- Healthcare delivery (hospitals, clinics, surgical suites)\n- Industrial/commercial settings (factories, food production)\n- Agricultural settings (farms, crop production)\n- Biological/physiological processes"
    ] = Field(..., title="Guidance Notes")


class ExtractionField3Literal(BaseModel):
    name: Literal["Research Process Waste Discussion"] = Field(..., title="Name")
    description: Literal[
        "Does this article discuss waste in the research process itself?"
    ] = Field(..., title="Description")
    field_type: Literal["text"] = Field(..., title="Field Type")
    required: Literal["True"] = Field(..., title="Required")
    question_number: Literal["3"] = Field(..., title="Question Number")
    question_type: Literal["screening"] = Field(..., title="Question Type")
    guidance_notes: Literal[
        "Reflect on whether the article addresses inefficiencies or problems in how research is conducted, reported, or used. Aspects of Research Waste (MINUS framework, Rosengaard et al, 2024; expanded): Methodological, Invisible, Negligible, Underreported, Structural, Emerging, Summative. Ask yourself: Is this about improving research quality and efficiency or about managing physical materials and operations?"
    ] = Field(..., title="Guidance Notes")


class AllowedValues(Enum):
    Asserted_research_waste = "Asserted_research_waste"
    Quoted_research_waste = "Quoted_research_waste"
    Food_waste = "Food_waste"
    Hazardous_waste = "Hazardous_waste"
    Plastic_waste = "Plastic_waste"
    Garbage_management = "Garbage_management"
    Industrial_waste = "Industrial_waste"
    Wastewater = "Wastewater"
    Medical_or_surgical_waste = "Medical_or_surgical_waste"
    Healthcare_personnel_time = "Healthcare_personnel_time"
    Excess_requisition = "Excess_requisition"
    Excess_use_of_animals = "Excess_use_of_animals"
    Pharmaceutical_waste = "Pharmaceutical_waste"
    Muscle_wasting = "Muscle_wasting"
    Metabolic_waste = "Metabolic_waste"
    Crop_residue = "Crop_residue"
    Not_sure_see_previous_step = "Not_sure_see_previous_step"


class ExtractionField4Literal(BaseModel):
    name: Literal["Waste Category"] = Field(..., title="Name")
    description: Literal["What waste category best describes this article?"] = Field(
        ..., title="Description"
    )
    field_type: Literal["categorical"] = Field(..., title="Field Type")
    required: Literal["True"] = Field(..., title="Required")
    question_number: Literal["4"] = Field(..., title="Question Number")
    question_type: Literal["flagging"] = Field(..., title="Question Type")
    allowed_values: AllowedValues = Field(..., title="Allowed Values")
    guidance_notes: Literal[
        "Select the single best category that describes the waste discussed in the article. Refer to the definitions for guidance on each category."
    ] = Field(..., title="Guidance Notes")
    conditional_logic: Literal[
        "Selection of 'Asserted_research_waste', 'Quoted_research_waste', or 'Not_sure_see_previous_step' will result in INCLUSION for Level 2 screening. Selection of any other category will result in EXCLUSION."
    ] = Field(..., title="Conditional Logic")


class Item(BaseModel):
    key: str = Field(..., title="Key")
    value: str = Field(..., title="Value")


class ExtractedValue1(BaseModel):
    step_0_extraction_field: ExtractionField1Literal
    step_1_initial_reflection_on_extracted_value: str = Field(
        ..., title="Step 1 Initial Reflection On Extracted Value"
    )
    step_2_initial_extracted_value: str = Field(
        ..., title="Step 2 Initial Extracted Value"
    )
    step_3_peer_reviewer_1_critical_comments_on_initial_extracted_value: List[str] = (
        Field(
            ...,
            title="Step 3 Peer Reviewer 1 Critical Comments On Initial Extracted Value",
        )
    )
    step_4_peer_reviewer_2_critical_comments_on_initial_extracted_value: List[str] = (
        Field(
            ...,
            title="Step 4 Peer Reviewer 2 Critical Comments On Initial Extracted Value",
        )
    )
    step_5_peer_reviewer_3_critical_comments_on_initial_extracted_value: List[str] = (
        Field(
            ...,
            title="Step 5 Peer Reviewer 3 Critical Comments On Initial Extracted Value",
        )
    )
    step_6_response_to_peer_reviewers_comments: str = Field(
        ..., title="Step 6 Response To Peer Reviewers Comments"
    )
    step_7_final_extracted_value: str = Field(..., title="Step 7 Final Extracted Value")


class ExtractedValue2(BaseModel):
    step_0_extraction_field: ExtractionField2Literal
    step_1_initial_reflection_on_extracted_value: str = Field(
        ..., title="Step 1 Initial Reflection On Extracted Value"
    )
    step_2_initial_extracted_value: str = Field(
        ..., title="Step 2 Initial Extracted Value"
    )
    step_3_peer_reviewer_1_critical_comments_on_initial_extracted_value: List[str] = (
        Field(
            ...,
            title="Step 3 Peer Reviewer 1 Critical Comments On Initial Extracted Value",
        )
    )
    step_4_peer_reviewer_2_critical_comments_on_initial_extracted_value: List[str] = (
        Field(
            ...,
            title="Step 4 Peer Reviewer 2 Critical Comments On Initial Extracted Value",
        )
    )
    step_5_peer_reviewer_3_critical_comments_on_initial_extracted_value: List[str] = (
        Field(
            ...,
            title="Step 5 Peer Reviewer 3 Critical Comments On Initial Extracted Value",
        )
    )
    step_6_response_to_peer_reviewers_comments: str = Field(
        ..., title="Step 6 Response To Peer Reviewers Comments"
    )
    step_7_final_extracted_value: str = Field(..., title="Step 7 Final Extracted Value")


class ExtractedValue3(BaseModel):
    step_0_extraction_field: ExtractionField3Literal
    step_1_initial_reflection_on_extracted_value: str = Field(
        ..., title="Step 1 Initial Reflection On Extracted Value"
    )
    step_2_initial_extracted_value: str = Field(
        ..., title="Step 2 Initial Extracted Value"
    )
    step_3_peer_reviewer_1_critical_comments_on_initial_extracted_value: List[str] = (
        Field(
            ...,
            title="Step 3 Peer Reviewer 1 Critical Comments On Initial Extracted Value",
        )
    )
    step_4_peer_reviewer_2_critical_comments_on_initial_extracted_value: List[str] = (
        Field(
            ...,
            title="Step 4 Peer Reviewer 2 Critical Comments On Initial Extracted Value",
        )
    )
    step_5_peer_reviewer_3_critical_comments_on_initial_extracted_value: List[str] = (
        Field(
            ...,
            title="Step 5 Peer Reviewer 3 Critical Comments On Initial Extracted Value",
        )
    )
    step_6_response_to_peer_reviewers_comments: str = Field(
        ..., title="Step 6 Response To Peer Reviewers Comments"
    )
    step_7_final_extracted_value: str = Field(..., title="Step 7 Final Extracted Value")


class ExtractedValue4(BaseModel):
    step_0_extraction_field: ExtractionField4Literal
    step_1_initial_reflection_on_extracted_value: str = Field(
        ..., title="Step 1 Initial Reflection On Extracted Value"
    )
    step_2_initial_extracted_value: Step2InitialExtractedValue = Field(
        ..., title="Step 2 Initial Extracted Value"
    )
    step_3_peer_reviewer_1_critical_comments_on_initial_extracted_value: List[str] = (
        Field(
            ...,
            title="Step 3 Peer Reviewer 1 Critical Comments On Initial Extracted Value",
        )
    )
    step_4_peer_reviewer_2_critical_comments_on_initial_extracted_value: List[str] = (
        Field(
            ...,
            title="Step 4 Peer Reviewer 2 Critical Comments On Initial Extracted Value",
        )
    )
    step_5_peer_reviewer_3_critical_comments_on_initial_extracted_value: List[str] = (
        Field(
            ...,
            title="Step 5 Peer Reviewer 3 Critical Comments On Initial Extracted Value",
        )
    )
    step_6_response_to_peer_reviewers_comments: str = Field(
        ..., title="Step 6 Response To Peer Reviewers Comments"
    )
    step_7_final_extracted_value: Step7FinalExtractedValue = Field(
        ..., title="Step 7 Final Extracted Value"
    )


class ExtractedValues(BaseModel):
    field_1: ExtractedValue1
    field_2: ExtractedValue2
    field_3: ExtractedValue3
    field_4: ExtractedValue4


class FlatDictLiteral(BaseModel):
    items: List[Item] = Field(..., title="Items")


class ExtractionSchema(BaseModel):
    document_type: Literal["Screening Cheatsheet"] = Field(..., title="Document Type")
    purpose: Literal[
        "To conduct a scoping review to identify articles discussing research waste in health and biomedical sciences, distinguishing them from other types of waste (e.g., medical waste, food waste, industrial waste)."
    ] = Field(..., title="Purpose")
    review_objective: Literal[
        "The goal is to conduct a scoping review to identify articles discussing research waste in health and biomedical sciences, distinguishing them from other types of waste (e.g., medical waste, food waste, industrial waste)."
    ] = Field(..., title="Review Objective")
    review_questions: Literal[
        "What constitutes research waste in health and biomedical sciences, and how can it be distinguished from other forms of waste in the literature?"
    ] = Field(..., title="Review Questions")
    project_details: Optional[FlatDictLiteral] = None
    global_instructions: GlobalInstructions = Field(..., title="Global Instructions")
    definitions: Optional[FlatDictLiteral] = None
    values: ExtractedValues
